[theme]
base = "dark"
primaryColor = "#FF003C"
backgroundColor = "#08020A"
secondaryBackgroundColor = "#15060A"
textColor = "#F0D6DC"
font = "sans serif"

[server]
headless = false
runOnSave = true

[browser]
gatherUsageStats = false
